spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.20.36.175/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #设置全局实体类属性值为null时不返回该字段
  jackson:
    default-property-inclusion: non_null

#定义整体项目前缀
server:
  servlet:
    context-path: /sell



wechat:
  mpAppId: wx557a6ea91652f1d1
  #mpAppId: wxd898fcb01713c658
  mpAppSecret: 338677634e7f31c11add1cc3314b2a6c
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://wxywizard.natapp1.cc/sell/pay/notify