spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.20.36.175/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

#定义整体项目前缀
server:
  servlet:
    context-path: /sell
